### ISSUE TITLE
What is this? 

### ISSUE THREAD

**Issue by Amber3232433** [GoogleCloudPlatform/bank-of-anthos#1031]
### Write down your inquiry 

I don't know what this is I didn't sign up for this what is it

**Comment by bourgeoisor** [comment]
Hi Amber; I'm not sure what your request is about, but in the event that you're receiving unwanted email notifications from this repositories, it's quite possible that you've unintentionally set bank-of-anthos to "watch". Make sure that you're not watching it. You can follow the following instructions:

- Navigate to https://github.com/GoogleCloudPlatform/bank-of-anthos
- Click the Watch button
- Click on Ignore

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3271352/196336175-376e2b80-7296-4b5d-b9f4-dabbdba1ef14.png">
