### ISSUE TITLE
How do I run the loadgenerator?

### ISSUE THREAD

**Issue by esraghu** [GoogleCloudPlatform/bank-of-anthos#1038]
I was looking for some help here on how to run the loadgenerator. I'm able to work with the frontend and push transactions. However not sure how the loadgenerator can be used to start pumping in transactions.

**Comment by bourgeoisor** [comment]
Hi! The `loadgenerator` workload should run by default. You can inspect its k8s logs (`kubectl logs pod/loadgenerator-<id>`) to see what it's doing. You can also tweak the amount of concurrent users here: https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/kubernetes-manifests/loadgenerator.yaml#L53-L54
Let me know if you have any specific questions.

**Comment by esraghu** [comment]
Thanks that was helpful @bourgeoisor 👍🏼
