### ISSUE TITLE
CI: Builds are running longer than expected

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#107]
## Expected Behavior
Continuous Integration builds should take around ~10 minutes to complete. 

## Actual Behavior
Several builds recently have taken 20 minutes or more: [Completed Pull Request Workflows](https://github.com/GoogleCloudPlatform/bank-of-anthos/actions?query=workflow%3A%22Continuous+Integration%22+event%3Apull_request+is%3Acompleted)

With the bulk of the time happening in the "Deploy from Source" step. Example: https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/575424795?check_suite_focus=true

**Comment by Daniel-Sanche** [comment]
**Some possible reasons for the recent slowdown:**
- dependency PRs have to rebuild containers from scratch
- the new python base images aren't tagged. This gives us all security updates for the base image, but it will probably mean more full rebuilds.
- our container images may be getting bloated. Each image needs to be copied into kind before being run, so large containers can be slow

**Possible solutions:**
- look at ways to optimize container image sizes
- find ways to run more tasks in parallel. This could be important as we add more unit/e2e tests to the pipeline
- the planned update to GKE CI may remove some of the local cluster slowness

**If we can't speed up tests, maybe we can at least cut down on the number of runs:**
- can we cancel previously scheduled CI runs when a new commit is pushed?
- do we really need to test the same commit in PR, and again once it's merged to master? If we can keep the same status, that could cut down on the number of runs
- more rest runners can help (https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/104)

**Comment by Daniel-Sanche** [comment]
@murog It looks like builds have been < 10 mind for > 1 week. Do you think this is safe to close?

**Comment by murog** [comment]
Seeing this issue again: https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/694609375?check_suite_focus=true

**Comment by bharathkkb** [comment]
Looks like some are getting stuck in queue as well.
https://github.com/GoogleCloudPlatform/bank-of-anthos/actions/runs/111756867
@Daniel-Sanche are we using an autoscaling MIG runner?

**Comment by Daniel-Sanche** [comment]
yeah, it looks like the smoke test is being extra flaky today. Good thing we're about to replace it with the UI tests

Auto-scaling isn't something we get for free with GitHub Actions. I've been tempted to build one custom (partially for security reasons), but it sounds like we're being asked to move to Cloud Build soon anyway, so we should probably just stay manual for now

**Comment by bharathkkb** [comment]
@Daniel-Sanche makes sense. If we don't have cloud build in the works for the near future, we can use [this](https://github.com/bharathkkb/terraform-google-github-actions-runners/tree/seed-tf-gh-runners) to spin up a MIG/GKE runner which will autoscale on demand.

**Comment by Daniel-Sanche** [comment]
Cool, I didn't know that was a thing! Yeah, if we do end up using GihHub Actions medium/long term that might be worth looking into more
