### ISSUE TITLE
Migrate to Artifact Registry from Container Registry

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/bank-of-anthos#1131]
* Today, Bank of Anthos uses Google Cloud's [Container Registry](https://cloud.google.com/container-registry/docs) for the container images that it published.
* For instance, `gcr.io/bank-of-anthos-ci/frontend:v0.5.10` is hosted on Container Registry.
* However, Artifact Registry is the recommended way to host container images on Google Cloud — not Container Registry.
* Relevant documentation: [Transition from Container Registry](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr).
* We should migrate to Artifact Registry.

### Additional Info
* I've created a similar GitHub issue on Online Boutique: https://github.com/GoogleCloudPlatform/microservices-demo/issues/1339, with a priority of `p2`.

**Comment by bourgeoisor** [comment]
As of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1221, all staging images are hosted in Artifact Registry (under `us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos`)

As of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1418, release images are also hosted in Artifact Registry.

No new images will land in Container Registry, but it will continue being active with images for versions `v0.5.11` and previous, to not break anyone's workflow.
