### ISSUE TITLE
Consider init containers one off Job pod for secret init

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#115]
This part of readme is slightly sad as it requires extra user interaction
to deploy the app, and requires another step of additional user interaction.

```
openssl genrsa -out jwtRS256.key 4096
openssl rsa -in jwtRS256.key -outform PEM -pubout -out jwtRS256.key.pub
kubectl create secret generic jwt-key --from-file=./jwtRS256.key --from-file=./jwtRS256.key.pub
```

AFAICT the resulting key is never used on developer machine and only lives in
the cluster (?). If that's the case, consider creating a one-off Job manifest
in kubernetes-manifests.yaml.

Istio's own deployment applies this practice (one-off Jobs).

Similarly, an initContainer for userservice may be also able to handle this,
though I'm not so sure about feasibility of that one as it depends on the
volume directly.

**Comment by Daniel-Sanche** [comment]
We try to get around the extra user interaction by using a pre-built secret manifest that's auto-deployed by skaffold run, but using a kubernetes job is a really interesting idea!

**Comment by Daniel-Sanche** [comment]
If we end up using kustomize, a (possibly simpler) option would be to use a [secretGenerator](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-secretGenerator)

FYI @ChandranshuRao14, if you were still thinking of taking this on
