### ISSUE TITLE
Cleanup script - missing dependencies

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos#116]
When I run the cleanup script, some scripts appear to be missing :

./env: line 10: /home/user/bank_of_anthos/bank-of-anthos-scripts/install/common/manage-state.sh: No such file or directory
./env: line 11: load_state: command not found
WORK_DIR set to /home/user/bank_of_anthos/bank-of-anthos-scripts/install/workdir
Updated property [core/project].
./cleanup.sh: line 32: ./connect-hub/cleanup-hub.sh: No such file or directory

**Comment by ChandranshuRao14** [comment]
Hey @dazdaz thanks for finding this bug. Can you open this issue in the `bank-of-anthos-scripts` repo? We can provide better tracking in that repo which is focused on the bootstrap scripts for deployment.

**Comment by ahmetb** [comment]
Someone who's an editor on both repos can use `Transfer issue` link on bottom right.

**Comment by dazdaz** [comment]
I'll close this issue as i've opened a new issue under the scripts repo, as requested.
