### ISSUE TITLE
Support for running bootstrap.sh from GCP GCE (Ubuntu VM)

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos#117]
Support for running the bootstrap.sh script from GCP GCE (Ubuntu VM).

Right now, the script is doing this check :
if [[ $OSTYPE == "linux-gnu" && $CLOUD_SHELL == true ]]; then

I'm not sure what pre-requisites need to be in place, but certainly kubectl and helm and kops and gcloud and kubectx need to be available.

**Comment by ChandranshuRao14** [comment]
See [this comment](https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/116#issuecomment-614171194)
