### ISSUE TITLE
Deployment dependency's - install kops into cloud shell

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos#118]
Perhaps someone can add in the dependency on kops being deployed within cloudshell into the README, to save on time debugging what the pre-requisites required actually are.

Installation is trivial :

curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
chmod +x kops-linux-amd64
sudo mv kops-linux-amd64 /usr/local/bin/kops

**Comment by ChandranshuRao14** [comment]
The bootstrap.sh executes `common/install-tools.sh` which should take care of all tooling dependencies if run in the Cloud Shell (see Kops [here](https://github.com/GoogleCloudPlatform/bank-of-anthos-scripts/blob/dc441f61da3c0fa00416b4b9798753fb053e04b9/install/common/install-tools.sh#L40)). Was kops installed in the `workdir` on your shell?

**Comment by ChandranshuRao14** [comment]
Also see [this comment](https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/116#issuecomment-614171194)

**Comment by dazdaz** [comment]
Closing ticket as requested, (wrong repo).
