### ISSUE TITLE
frontend should be exposed via istio gateway?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#119]
It seems frontend svc has type:LoadBalancer. If the demo always will use Istio,
why not just integrate to the istio ingressgateway?

**Comment by Daniel-Sanche** [comment]
Right now, this build of the app doesn't include Istio. Megan has a seperate repo with Istio set up, but there are a couple outstanding issues with multicluster Istio that are still being worked on
