### ISSUE TITLE
Weird image names upon skaffold deployment

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#121]
I get image names like `gcr.io/ahmetb-demo/bank-of-anthos/gcr.io/bank-of-anthos/ledger-db`
is that expected? It's technically not harmful, just looks buggy.

**Comment by Daniel-Sanche** [comment]
This seems to be the intended behaviour of [skaffold image name rewriting](https://skaffold.dev/docs/environment/image-registries/)
