### ISSUE TITLE
Migrate to Spring 6 / Boot 3

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/bank-of-anthos#1217]
Currently, we're using Sprint Boot 2.7. In November 2022, both Spring 6 and Boot 3 came out.

We should look at what migration steps are needed on our end to be able to upgrade to that release, which is likely not nil based on some failed attempts at automatically upgrading:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1117
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1171

There is an official migration guide here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

See also: https://spring.io/blog/2022/12/16/spring-cloud-2022-0-0-codename-kilburn-has-been-released

**Comment by Mukamik** [comment]
Submitted a PR to address these issues:
https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1250
