### ISSUE TITLE
easier to read IP command

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#126]
consider replacing this command in README.md:

    kubectl get svc frontend | awk '{print $4}'

with

    kubectl get service frontend --output=jsonpath='{.status.loadBalancer.ingress[0].ip}'

**Comment by Daniel-Sanche** [comment]
The downside to this is it returns nothing when the IP is pending. It's more reliable for scripting, but arguably not as human friendly

**Comment by ahmetb** [comment]
Yeah that's valid. Feel free to close.
