### ISSUE TITLE
inconsistent liveness/readiness probe usage

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#127]
Some services have livenessProbe+readinessProbe and some just readinessProbe.
Is there a reason why?

Couple of interesting articles on usage of "liveness" probes:
- https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
- https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/

**Comment by Daniel-Sanche** [comment]
My interpretation of the "liveness probes are dangerous" post is that not every service needs a liveness probe, right? The services that use multiple threads use liveness probes to detect if the background thread died, to terminate the service. Simpler services just use a readiness probe
