### ISSUE TITLE
User Id not working

### ISSUE THREAD

**Issue by crispindev** [GoogleCloudPlatform/bank-of-anthos#132]
Just tried to login with the default credentials and it did no login, can´t see the topology on Anthos UI.

**Comment by djmailhot** [comment]
What build/version are you using?

The default credentials work for me on `master` (Latest commit `c1d468f` 20 hours ago), as well as on `release/v0.1.0`

**Comment by crispindev** [comment]
I used that released and got the error. I had to use (this commit `85a8638`) for it to run.

**Comment by Daniel-Sanche** [comment]
Is it possible you had an older version of the app installed in your cluster? We recently updated from deployments to statefulsets for the databases. If you had the existing deployments in your cluster, you may have to remove them

**Comment by cgrant** [comment]
I'm getting the same issue, just pulled from master. The default testuser is throwing a 404 from the userservice. however I can log in with the other uuid accounts being generated

The accountdb logs start with:
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/1-load-testdata.sh
Error: environment variable 'TEST_ACCOUNTID' not set. Aborting.
```
on further inspection it appears that there was a [commit here](https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/5a8d7772e5f9d71bdeb239e345d984c08b548ee1#diff-2933af3d33a5cff9e8f965b9133c3720) that moved to use the config-map instead. 

I believe the image being pulled [from here](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/kubernetes-manifests/accounts-db.yaml#L37) may not be updated to reflect the config map update

**Comment by Daniel-Sanche** [comment]
@cgrant Good catch. This made me realize our CI system is testing the latest builds of the code, but not testing the manifests with the latest published images. I opened up https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/150 to push a hotfix, and https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/151 to ensure this is tested going forward

**Comment by Daniel-Sanche** [comment]
The new v0.1.1 images that should solve this. https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/153 should make sure it's tested. I'm closing this now, but let me know if it's still an issue
