### ISSUE TITLE
Add ENV_PLATFORM flag to frontend / UI

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#137]
Example - 

<img width="1718" alt="online-boutique-frontend-1" src="https://user-images.githubusercontent.com/3137106/80098891-a077ec80-853b-11ea-94a6-82204bfbc156.png">

Setting the `ENV_PLATFORM` variable in the frontend manifest (gcp, aws, onprem, azure) updates a flag on the left side of the frontend. The flag changes colors based on environment. 
This will be useful for hybrid setups / if we distribute the frontend in multiple environments.

**Comment by bourgeoisor** [comment]
This is part of our demo enablement story but still in the backburner.
