### ISSUE TITLE
Parameterize the gcr.io image tag in manifest files

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#143]
Currently every kubernetes manifest file is hardcoded to reference gcr.io docker images with a particular tag:
`gcr.io/bank-of-anthos/ledgerwriter:v0.1.0`

We should parameterize the tag `v0.1.0` so that deployments can easily switch between release versions, or latest builds during development.

**Comment by Daniel-Sanche** [comment]
Adding our own parameters here would break the "kubectl apply" workflow. We want people to be able to quickly deploy the latest release of the app (or whatever version was current, if they view old tags).

I think we're better off relying on skaffold for rewriting the image tag during development, this is the use case it was built for after all
