### ISSUE TITLE
Send payment to self fails without contact label 

### ISSUE THREAD

**Issue by meganzhao10** [GoogleCloudPlatform/bank-of-anthos#155]
When sending payment to the same account without contact label, 500 error is thrown.

**Comment by Daniel-Sanche** [comment]
Just reproduced this. Sending a payment to yourself loads a 500 error page instead of just displaying an error message in the UI

Maybe we should add this as a UI test case @murog?

**Comment by Daniel-Sanche** [comment]
This should be fixed now on master
