### ISSUE TITLE
Update Java package to be anthos.samples.bankofanthos

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#167]
Currently the Java code is packaged under `anthos.samples.financedemo`.  We should change that to `anthos.samples.bankofanthos`.

The name **financedemo** is the original title of this demo.  We should update to use the current title of **Bank of Anthos**.

**Comment by AydarZaynutdinov** [comment]
Hello! I want to help with this issue and I want to make contributions. Can I make it?
