### ISSUE TITLE
Releasing manifests should not have a default namespace set

### ISSUE THREAD

**Issue by debakkerb** [GoogleCloudPlatform/bank-of-anthos#1698]
### Write down your inquiry 
Is there a reason why the `default` namespace was introduced to the manifests?  Here is an [example](https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/95433301585fc9657886edb6229eed25311df15a).  If you want to install the application in a different namespace, you have to update all of them either manually or via `sed`, while in the past you could just pass in the `--namespace` target while running `kubectl apply`.  

Is it possible to revert this change?

**Comment by bourgeoisor** [comment]
@debakkerb Thanks for flagging this.

>  there a reason why the default namespace was introduced to the manifests?

No. This is an oversight.

I've just pushed a hot-fix: https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/e7878e557ba069e0181cc9d3bac3e74378dc4268

Sorry for any disruptions this may have caused.

Feel free to close the issue if this solved your issue; and if not let me know!
