### ISSUE TITLE
JVM_OPTS are not being applied to container JVMs for Anthos java apps

### ISSUE THREAD

**Issue by uselessjargon** [GoogleCloudPlatform/bank-of-anthos#1784]
Hi All,
I've been using this app to extend my knowledge of JVM performance tuning in a Kubernetes environment and found that the java applications aren't actually using the JVM_OPTS env var that is set in the deployment yamls. 

I was able to get JVM_OPTS working by updating the application's pom.xml with a custom entrypoint in the jib section and thought I'd share the fix. 

Without this custom entrypoint in place, the current `-Xms` and `-Xmx` settings in the JVM_OPTS env var for ledgerwriter in Kubernetes (**and other java apps in this repo**) won't be applied to the JVM upon start. This likely is only an issue for anyone trying to tune the JVMs under varying load conditions as the current settings should use 25% of the container memory for the JVM max heap.

I came across the issue trying to enable JMX on the ledgerwriter app in its deployment yaml.  No matter what settings I added the to the JVM_OPTS env var in the deployment yaml, the JMX port wouldn't listen within the container. Once I added the custom entrypoint for the container in the pom.xml and rebuilt the image I was able to see the JMX port listening. 

For reference, below is the current entrypoint in the ledgerwriter image before adding the custom entrypoint:
```
docker inspect us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledgerwriter:v0.6.1
...
            "Entrypoint": [
                "java",
                "-cp",
                "@/app/jib-classpath-file",
                "anthos.samples.bankofanthos.ledgerwriter.LedgerWriterApplication"
            ],
...
```

As stated above, the way I was able to fix the issue is to add a custom entrypoint. I added the custom entrypoint by adding the `<container>` section below to the app's src/pom.xml (e.g., `bank-of-anthos/src/ledgerwriter/pom.xml`)
```xml
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <from>
                        <image>eclipse-temurin:17.0.4.1_1-jre-alpine</image>
                    </from>
                    <container>
                      <entrypoint>
                        <arg>/bin/sh</arg>
                        <arg>-c</arg>
                        <arg>exec java $JVM_OPTS -cp @/app/jib-classpath-file @/app/jib-main-class-file</arg>
                      </entrypoint>
                    </container>
                </configuration>
            </plugin>
```

After the above custom entrypoint is added to application's pom.xml and the image is rebuilt, the entrypoint looks like this:
```
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "exec java $JVM_OPTS -cp @/app/jib-classpath-file @/app/jib-main-class-file"
            ],
            "OnBuild": null,
            "Labels": {}
        },
```

And with the updated entrypoint, the JMX port is now listening within the container as can be seen below.

Checking JVM_OPTS env var in container:
```
~/bank-of-anthos/kubernetes-manifests$ kb exec -it ledgerwriter-6c96b55cb9-vf944 -- env | grep JVM_O
PTS
JVM_OPTS=-Xms256m -Xmx512m -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
```

Check listening ports in the container:
```
bank-of-anthos/kubernetes-manifests$ kb exec -it ledgerwriter-6c96b55cb9-vf944 -- netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 :::5000                 :::*                    LISTEN      1/java
tcp        0      0 :::8080                 :::*                    LISTEN      1/java
tcp        0      0 :::37043                :::*                    LISTEN      1/java
```

The args  can also be seen in the Java process output:
```
~/bank-of-anthos/kubernetes-manifests$ kb exec -it ledgerwriter-6c96b55cb9-vf944 -- sh
/ $ ps -ef | grep java
    1 1000      0:41 java -Xms256m -Xmx512m -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp /app/resources:/app/classes:/app/libs/spring-boot-starter-web-2.7.5.jar:/app/libs/spring-boot-starter-2.7.5.jar:/app/libs/spring-boot-2.7.5.jar:/app/libs/spring-boot-autoconfigure-2.7.5.jar:/app/libs/spring-boot-starter-logging-2.7.5.jar:/app/libs/logback-classic-1.2.11.jar:/app/libs/logback-core-1.2.11.jar:/app/libs/log4j-to-slf4j-2.17.2.jar:/app/libs/jakarta.annotation-api-1.3.5.jar:/app/libs/spring-core-5.3.23.jar:/app/libs/spring-jcl-5.3.23.jar:/app/libs/snakeyaml-1.30.jar:/app/libs/spring-boot-starter-json-2.7.5.jar:/app/libs/jackson-datatype-jdk8-2.13.4.jar:/app/libs/jackson-datatype-jsr310-2.13.4.jar:/app/libs/jackson-module-parameter-names-2.13.4.jar:/app/libs/spring-boot-starter-tomcat-2.7.5.jar:/app/libs/tomcat-embed-core-9.0.68.jar:/app/libs/tomcat-embed-el-9.0.68.jar:/app/libs/tomcat-embed-websocket-9.0.68.jar:/app/libs/spring-web-5.3.23.jar:/app/libs/spring-beans-5.3.23.jar:/app/libs/spring-webmvc-5.3.23.jar:/app/libs/spring-aop-5.3.23.jar:/app/libs/spring-context-5.3.23.jar:/app/libs/spring-expression-5.3.23.jar:/app/libs/spring-boot-starter-data-jpa-2.7.5.jar:/app/libs/spring-boot-starter-aop-2.7.5.jar:/app/libs/aspectjweaver-1.9.7.jar:/app/libs/spring-boot-starter-jdbc-2.7.5.jar:/app/libs/HikariCP-4.0.3.jar:/app/libs/spring-jdbc-5.3.23.jar:/app/libs/jakarta.transaction-api-1.3.3.jar:/app/libs/jakarta.persistence-api-2.2.3.jar:/app/libs/hibernate-core-5.6.12.Final.jar:/app/libs/jboss-logging-3.4.3.Final.jar:/app/libs/antlr-2.7.7.jar:/app/libs/jandex-2.4.2.Final.jar:/app/libs/classmate-1.5.1.jar:/app/libs/hibernate-commons-annotations-5.1.2.Final.jar:/app/libs/jaxb-runtime-2.3.7.jar:/app/libs/jakarta.xml.bind-api-2.3.3.jar:/app/libs/txw2-2.3.7.jar:/app/libs/istack-commons-runtime-3.0.12.jar:/app/libs/jakarta.act
```

# !! Please Note !!
The current JVM_OPTS of `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` will need to be removed in the deployment yaml's once the custom entrypoint is applied since the `UseCGroupMemoryLimitForHeap`  is no longer valid for the JVM version being used in the applications (I believe that feature is built in by default in Java 17). Since we're not setting `-XX:+UseCGroupMemoryLimitForHeap` there is no need for `-XX:+UnlockExperimentalVMOptions` unless there are other experimental settings you want to explore. If `-XX:+UseCGroupMemoryLimitForHeap` is left in JVM_OPTS the pod will fail to start with the below message.

```
~bank-of-anthos/kubernetes-manifests$ kb logs ledgerwriter-64c8fcbdb4-wkh8r
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by bourgeoisor** [comment]
I believe this was fixed in https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1795

Feel free to reopen if you're still seeing this issue with the latest release.
