### ISSUE TITLE
UI Test: cannot contain more than 2 decimal digits

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#182]
## Description
Test case: Transfer / Deposit cannot contain more than 2 decimal digits
Manual testing shows that the UI is exhibiting correct behavior.  However, Cypress UI tests fail and round to `5.01`

## Expected behavior
Test reflects:
![Screen Shot 2020-05-20 at 1 47 07 PM](https://user-images.githubusercontent.com/12957039/82495761-749b4880-9aa0-11ea-8641-a34c064b713d.png)
```
    it('cannot contain more than 2 decimal digits', function () {
        const invalidPayment = `5\.02\.35\.459`
        cy.transfer(recipient, invalidPayment)
        cy.get('.invalid-feedback').should('be.visible')
        cy.get('.invalid-feedback').contains(invalidFeedback.payment)
```

### Current behavior
![Transfer is unsuccessful with invalid data -- cannot contain more than 2 decimal digits (failed)](https://user-images.githubusercontent.com/12957039/82495628-3dc53280-9aa0-11ea-95e3-13658e56359e.png)

**Comment by NimJay** [comment]
Update: This will be fixed in #548.
We should be able to resolve sometime in January (with @Shabirmean's help, when he's back in the office). :)
(Commenting to cool down this ticket from our dashboard.)
