### ISSUE TITLE
Add database persistent storage

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#189]
For in-cluster DBs.

**Comment by Daniel-Sanche** [comment]
We use stateful sets, so it should be pretty easy to attach a storage volume, but so far I've held back for compatibility reasons (we don't want a hard dependency on GCP, don't want to worry about local storage differences between minikube/kind, don't want to have to deal with bugs that arise when deploying new versions over existing data...).

If we're getting requests to add storage, I'd suggest doing it in a kustomize overlay so the default deployment stays simple. Or when we add CloudSQL that will store persistently by default, so it might just be better to just show CloudSQL when we want to tell that story
