### ISSUE TITLE
extras/istio-manifests/ does not exist

### ISSUE THREAD

**Issue by arueth** [GoogleCloudPlatform/bank-of-anthos#1977]
### Describe the bug 
`extras/istio-manifests/` does not exist

### Additional context
In the **Additional deployment options** section of the [README.md](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/README.md) file it states:

- **Anthos Service Mesh**: ASM requires Workload Identity to be enabled in your GKE cluster. [See the workload identity instructions](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/workload-identity.md) to configure and deploy the app. Then, apply `extras/istio-manifests/` to your cluster to configure frontend ingress.

**Comment by arueth** [comment]
It looks like it was moved to `extras/istio`

**Comment by arueth** [comment]
It is also references in https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/extras/asm-multicluster

**Comment by bourgeoisor** [comment]
Good catch-- Yes those are omissions. `istio-manifests` was moved to `istio`. I can fix those in docs later this week, or you can, whoever gets to it first. :)
