### ISSUE TITLE
Deposit resulting in "sender not authenticated"

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#199]
### Steps to Reproduce
1. Followed steps to create new BoA deployment
1. Created new account
1. Make deposit to new external account without account label

🚨 Flaky, only happened the first three times
### Expected Behavior
![image](https://user-images.githubusercontent.com/12957039/83214722-1e6e7b00-a11a-11ea-9f3f-70fdcb1f2459.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/12957039/83214681-07c82400-a11a-11ea-8f26-005f38df06e8.png)

**Comment by murog** [comment]
If not reproducible could be helpful to have short documentation on revolving common error messages?

**Comment by askmeegs** [comment]
TODO - check service logs in userservice

**Comment by murog** [comment]
[message source: lederwriter](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/e67011bdba45144a99fd70dfbcb48e12c4d1f137/src/ledgerwriter/src/main/java/anthos/samples/financedemo/ledgerwriter/TransactionValidator.java#L81)

**Comment by murog** [comment]
haven't been able to reproduce or find information in logs, closing for now

**Comment by Daniel-Sanche** [comment]
I'm thinking this may have something to do with the token expiring. The tokens are set to [expire after an hour](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/4bdc25daf21a5f8b7a945380b1be9a60626e7de9/kubernetes-manifests/userservice.yaml#L45), and then the user should be sent back to the login page, but maybe there's a bug in there somewhere. Might be worth exploring at some point to see if we can reproduce this

**Comment by murog** [comment]
I was able to reproduce again
1. Followed steps to create new BoA deployment
1. Login with default user
1. Make deposit without contact label

**Comment by Daniel-Sanche** [comment]
Ok, I found the issue! This is a weird one that hits a weird edge case:

- 123456789 is the bank of Anthos routing number. By using that as the "external deposit" routing number, our backend is treating it as an internal transaction
- your account isn't 1234567890, but now you're trying to initiate an internal transaction on their behalf, so the backend rejects it

The LedgerWriter is actually kind of behaving properly in this case. I'll add an extra check in the frontend to give a more appropriate error message though
