### ISSUE TITLE
realpath -s not supported on MacOS Sequoia

### ISSUE THREAD

**Issue by rcastley** [GoogleCloudPlatform/bank-of-anthos#2238]
Please check the [open issues](https://github.com/GoogleCloudPlatform/bank-of-anthos/issues) for this repository to verify that the same `issue/bug` has not been already reported. 

If you see the bug being already reported, please upvote and comment on the existing issue instead of opening a new one. If you notice a `bug/issue` which is not the same as yours but is related, create a new one and link to the existing `bug/issue`.

### Describe the bug 
`make-release.sh` using `realpath -s` which is not supported on MacOS Sequoia.

### To Reproduce 
Run the `make-release.sh` script on MacOS Sequoia

### Suggested Fix
Replace:

```bash
SCRIPT_DIR=$(dirname $(realpath -s $0))
```

with

```bash
SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")
SCRIPT_DIR="$(dirname $SCRIPT_PATH)"
```

### Environment 
MacOS Sequoia

**Comment by glasnt** [comment]
Can you confirm the output of `which realpath`? I've updated my machine to Sequoia (but haven't updated Xcode), so I'm currently able to use realpath. 

```
$ which realpath
/bin/realpath
```

**Comment by bourgeoisor** [comment]
I'm noticing the `-s` is gone from Sonona as well (or at least it is on my ARM machine -- Maybe it's an ARM thing?)

It was a superfluous flag only for a very edge case that the majority of people shouldn't encounter anyway, so I just removed it here: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/2256
