### ISSUE TITLE
loadgenerator image build failing

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/bank-of-anthos#2247]
### Describe the bug 

`build-and-push-images` step in pull-request-ci is failing due to build issues on loadgenerator

### Logs  
[PR 2246 broken CI](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/2246/checks?check_run_id=32197944164)
[PR 2244 working CI](https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/32133237407)

### Environment 
 Cloud Build

### Additional context 

It appears https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/2242 was auto opened and auto-merged, which introduced Python 3.13, but gevent family of deps are building from source, and failing due to lack of build deps (a python slim docker container). 

Updating the one dependency `locust` to latest available and building the container failed; changing the base image from  python:3.13.0 to  python:3.13.0-slim does work, but it will make the image larger than possibly intended, and take longer than intended. 

180MB / 1.1 minutes on Python 3.12 Slim
vs
1083MB / 0.5 Minutes on Python 3.12 (full)

Just building the image with Cloud Build, not the skaffold command from the CI itself .

**Comment by bourgeoisor** [comment]
Looks like that PR had a failed CI, so I have no idea why (and slightly annoyed at the fact that) the merge-on-green bot auto-merged that. Reverting here: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/2249
