### ISSUE TITLE
Redundant catch statement in balancereader service

### ISSUE THREAD

**Issue by WilliamG240** [GoogleCloudPlatform/bank-of-anthos#230]
Going through the balancereader service I noticed a redundancy in the try catch behaviour in the `getBalance` function of `BalanceReaderController.java`, where we check if the user is authorized to access an account through an if statement but we still catch a `JWTVerificationException` error.

**Comment by Daniel-Sanche** [comment]
It's actually not redundant:
- `JWTVerificationException` is thrown if the JWT isn't valid (it's malformed, signature doesn't match payload, or is expired)
- The if statement catches the case where the JWT is valid, but for a different user. (I shouldn't be able to use my login token to transfer money from your account)

[[This is a link to the code for future reference](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/f8ca0e3615298f586d740263e428b5ca066b6be4/src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/BalanceReaderController.java#L196)]
