### ISSUE TITLE
UI Tests: Add local cypress profile with fixtures and stubbed services calls 

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#280]
## Description
We currently use Cypress for integration tests, so all of the calls are made against live services.  It would be nice to have a cypress profile that uses fixtures and stubbed service calls.  This would enable future UI work to be tested locally and quickly, without needing a full deployment.

**Comment by askmeegs** [comment]
Closing as low priority / the frontend has stabilized.
