### ISSUE TITLE
[Actions runner] Add cleanup job to avoid running out of disk space 

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#351]
Some CI process (tools install / upgrade?) is creating a 1GB `image-tar` file in the `/tmp` directory that doesn't get auto-deleted. This causes the disk space to fill up over time. Find a way to auto-remove these files. 

Example: 

```
mokeefe@github-actions-ci:/tmp$ ls -la
total 376
drwx------  2 sanche  sanche    4096 May 20 21:24 image-tar016521277
````

**Comment by donmccasland** [comment]
I've checked all failed builds for the last three months and fall no more evidence of this issue.  Additionally, I've run all the current github actions and no /tmp/*tar* files were created on the runners.
