### ISSUE TITLE
Parallelize frontend HTTP calls to backend APIs

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#353]
Currently the homepage makes 3 HTTP calls in sequence to backend APIs, adding up to almost 2 seconds of extra latency to the webpage.

![frontend_trace](https://user-images.githubusercontent.com/704680/93397884-59aeca00-f82f-11ea-9b44-ae65024506d3.png)

 These HTTP calls should be parallelized.

**Comment by bourgeoisor** [comment]
I think we should still do this. Commenting to reset SLO.

**Comment by bourgeoisor** [comment]
We should still do this. Commenting to reset SLO.
