### ISSUE TITLE
Convert Python services from SQLAlchemy ORM to SQLAlchemy Core 

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#361]
Hypothesis: SQLAlchemy adds latency to requests, whereas raw SQL does not. 

See draft PR: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/357

**Comment by cloud-pharaoh** [comment]
From previous experience with multiple applications using sqlachemy, we switched to [SQLAlchemy Core](https://docs.sqlalchemy.org/en/13/core/) and saw a huge reduction in latency overhead and still had some benefits. TBH, I can't remember why we didn't just switch to psycopg2 and raw queries but I recall SQLAlchemy still had some good uses.

**Comment by askmeegs** [comment]
Closing as the latency observed in Sept 2020 was due to a separate tracing issue (wrong span exporter used instead of batch). Will deprioritize SQLAlchemy Core work for now.
