### ISSUE TITLE
Flaky Tests: create spec

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#368]
## Description
`User can create account contain zero balance` Test is currently failing in https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/1151325914?check_suite_focus=true  Test has not been flaky in the past (#223)

**Comment by murog** [comment]
https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/1155459689?check_suite_focus=true
```
  1) User can create account
       contain zero balance:
     AssertionError: Timed out retrying: Expected to find element: `#current-balance`, but never found it.
      at Context.eval (http://34.123.23.247/__cypress/tests?p=cypress/integration/create_spec.js:185:8)
```

**Comment by murog** [comment]
Create spec is run first and might be flaky because service is not ready yet.  PR #360 added a 1 minute sleep before Cypress tests are run.  Flakiness was seen again here: https://github.com/GoogleCloudPlatform/bank-of-anthos/runs/1160336179?check_suite_focus=true.   Could be helpful to use the [wait-on](https://github.com/cypress-io/cypress-docker-images/tree/master/included#wait-on) utility that the cypress/included docker image provides

**Comment by donmccasland** [comment]
Meegs, can you comment on this one?

**Comment by askmeegs** [comment]
Sorry for the delay on replying here -- I believe this issue still stands but we haven't had breaking UI tests for a while. It could be that the combination of the Python trace latency fix + the ongoing readiness probe issue fix resolved this. But need to double check / try to reproduce. 

Unassigning myself in case someone else wants to pick this up during the Q2 rotation.

**Comment by askmeegs** [comment]
Closing as outdated, will reopen if we see this bug again in breaking UI tests in our CI.
