### ISSUE TITLE
Create custom config.yaml for ledgermonolith with skaffold custom build command

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#401]
Currently, ledgermonolith must create a custom config.yaml from a template file to correctly deploy the Java monolith version of the app.  This custom config.yaml is created only with the command `make monolith`.  There are currently no clear manual steps to create the custom config.yaml.

This custom config.yaml could be created as part of the skaffold script with a [custom build command](https://skaffold.dev/docs/tutorials/custom-builder/)

**Comment by askmeegs** [comment]
Closing in favor of future kustomize support - #486
