### ISSUE TITLE
Test Cloud SQL with Anthos Service Mesh enabled

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#407]
Test with ASM-enabled cluster to verify Cloud SQL proxy -> Cloud SQL connectivity when there is another sidecar container in the pod (Envoy).

**Comment by cloud-pharaoh** [comment]
Megan, I have this deployed as part of the reference architecture with ASM 1.8 and it is working as expected.

**Comment by cloud-pharaoh** [comment]
https://gitlab.com/aminamansour/anthos-gcp-ref-arch
