### ISSUE TITLE
Prod cluster frontend readiness probe fails every 3-4 days

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#447]
```
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  4m28s (x61 over 26h)  kubelet  Readiness probe failed: Get http://10.44.1.40:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by Shabirmean** [comment]
Issue update:

Mostly seeing socket errors during and around the time when the probe fails:
```
2021-02-11 17:28:41 | [ERROR] | exception | Socket error processing request.
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 266, in handle
    req = next(conn.parser)
  File "/env/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/env/lib/python3.7/site-packages/gunicorn/http/message.py", line 186, in __init__
    super().__init__(cfg, unreader)
  File "/env/lib/python3.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/env/lib/python3.7/site-packages/gunicorn/http/message.py", line 235, in parse
    self.headers = self.parse_headers(data[:idx])
  File "/env/lib/python3.7/site-packages/gunicorn/http/message.py", line 73, in parse_headers
    remote_addr = self.unreader.sock.getpeername()
OSError: [Errno 107] Transport endpoint is not connected
```

The issue can be related to the `gunicorn` server. Many people have raised the same behaviour for `Flask` and `Django` applications using `gunicorn` here: https://github.com/benoitc/gunicorn/issues/1913

Most of them reported the intermittent behaviour in `AppEngine` and `CloudRun` in GCP for their Apps. Someone actually discovered the issue (https://github.com/benoitc/gunicorn/issues/1913#issuecomment-601255354) to be a race-condition causing the server to crash once every now and then and opened a PR: https://github.com/benoitc/gunicorn/pull/2277

The PR was merged but there has not been a release of a newer version of `gunicorn` yet. They are still discussing and according to this thread (https://github.com/benoitc/gunicorn/issues/1913#issuecomment-762490975) they have asked to Watch for a release.

Options would be to either migrate from `gunicorn` to some other application server or wait for a `gunicorn` release that includes the above and re-deploy.
