### ISSUE TITLE
Intermittent errors related to writing to Cloud Trace in frontend

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/bank-of-anthos#451]
There are intermittent `Cloud Trace` specific errors in the frontend logs

```
[ERROR] | export | Error while writing to Cloud Trace
```

![image](https://user-images.githubusercontent.com/7249208/107695026-0d50a480-6c7e-11eb-9054-3fa6832a8f36.png)

**_GCP Cloud Logging Query:_**
```
resource.type="k8s_container"
resource.labels.project_id="<PROJECT_ID>"
resource.labels.location="<REGION>"
resource.labels.cluster_name="<CLUSTER>r"
resource.labels.namespace_name="<NAMESPACE>"
labels.k8s-pod/app="frontend"
"[ERROR]"
-textPayload=~"^.*([ERROR] | payment | Error submitting payment: insufficient balance\n)"
```

**Comment by bourgeoisor** [comment]
@Shabirmean could you tell me more about this deployment of Bank of Anthos and if you had just deployed a vanilla cluster in GKE or if you had added extra options or configuration to it?

I deployed the latest commit last night and queried through the past 12 hours of logs but did not find any logs relating to Cloud Trace in any of the containers:
![image](https://user-images.githubusercontent.com/3271352/128908417-b2a6ac39-018f-436c-b0ab-388d8a2a89dc.png)

**Comment by bourgeoisor** [comment]
I've looked through the current production logs for Bank of Anthos and can only see two instances of that log in the past 7 days:
![image](https://user-images.githubusercontent.com/3271352/128932110-15ab18ef-6409-44f5-971a-0c822fab6950.png)
And one of those logs (the August 7th one) coincide with Bank of Anthos booting up:
![image](https://user-images.githubusercontent.com/3271352/128932333-dd49dbc2-87c6-4222-b849-5582b0169000.png)

**Comment by bourgeoisor** [comment]
I let the two deployments run for another 24 hours and didn't see this error show up again. It seems to only happen during the boot sequence (which I consider normal, given that not all Pods are ready and fully up-and-running), and very occasionally if there is a network hiccup (and even then I've only seen a single example of this in the past week+).
I will close this bug for now. Feel free to reopen if you have more information or can reproduce it outside of boot-up / network hiccups.
