### ISSUE TITLE
Create Account page - address and zip code fields not editable

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#464]
<img width="907" alt="Screen Shot 2021-03-04 at 12 56 32 PM" src="https://user-images.githubusercontent.com/3137106/110007802-0fd87400-7ce9-11eb-947a-3bfd1fbeeaa9.png">

**Comment by Shabirmean** [comment]
We are tracking this in our upcoming roadmap for this app next year!
