### ISSUE TITLE
Add Cloud Logging structured logs for Java and Python services

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#498]
Only seeing this mislabeled severity with `INFO` logs --> mistakenly logged as `ERROR`. 

Services where I see this: **userservice**, **contacts**, and **frontend** (all the python services), the two in-cluster databases (**accounts** and **ledger**). Java services are unaffected. 

Example: 

<img width="894" alt="Screen Shot 2021-06-03 at 1 41 38 PM" src="https://user-images.githubusercontent.com/3137106/120688848-79dff100-c471-11eb-8bd1-d7da5e614cd0.png">

Strangely, [the line of code there is `app.logger.info`](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/src/frontend/frontend.py#L394) but it's getting mislabeled in severity, somewhere.

**Comment by askmeegs** [comment]
Tested with an older, pre-UWSGI (gunicorn instead) version of the Python services -- release v0.2.0 https://github.com/GoogleCloudPlatform/bank-of-anthos/releases/tag/v0.2.0 

Reason for testing that older version is Gunicorn had a separate logging.conf for the 3 python services, which we lost when we moved to UWSGI https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/3ea9ebc1382ebc98133e6b17e532a99369404807/src/frontend/logging.conf 

But the "info as error" bug seems to date back to when we had Gunicorn - seeing the same behavior on 0.2.0. 

The databases (Postgres) logging errors as info seems to be a separate, ongoing issue.

**Comment by askmeegs** [comment]
After diving into the code + history + recommended ways of doing Python + Google Cloud Logging, I don't know if we ever set this up correctly, I think the log level has always rendered wrong in Cloud Logging.

Looking at the Cloud Ops Sandbox's python services -- [example](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/master/src/emailservice/logger.py) -- they have set up structured JSON logging using [python-json-logger](https://github.com/madzak/python-json-logger), overriding the severity field to correctly populate it before sending it to Cloud Logging. I've replicated this in the Python services and now the level is showing up correctly. Note that only the "message" shows up in the cloud logging message field, not  

For consistency, I updated the Java service logs to use structured JSON as well, so that only the message shows up in the cloud logging message, not `level / method / message` / ` | [INFO] | login | Login Successful.` - Users can still see these fields (like func name) in the JSON stdout -- 

**Python stdout** - 

```json 
frontend-8577ff7fbf-czczh front {"asctime": "2021-06-04 21:56:19,445", "levelname": "INFO", "funcName": "payment", "message": "Payment initiated successfully.", "timestamp": 1622843779.445502, "severity": "INFO"}
```

**Java stdout**: 

```
ledgerwriter-5494dcbcd5-9l8cl ledgerwriter {"thread":"main","level":"INFO","loggerName":"org.springframework.cloud.context.scope.GenericScope","message":"BeanFactory id=b2d1a364-a716-3809-a52f-510193dbe410","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.LogAdapter$Log4jLog","instant":{"epochSecond":1622844203,"nanoOfSecond":266000000},"contextMap":[],"threadId":1,"threadPriority":5,"source":{"method":"setSerializationId","file":"GenericScope.java","line":295,"class":"org.springframework.cloud.context.scope.GenericScope"},"time":"2021-06-04T22:03:23.266Z"}
```

And they can see those fields in the cloud logging UI -- 

<img width="582" alt="Screen Shot 2021-06-04 at 5 03 56 PM" src="https://user-images.githubusercontent.com/3137106/120862396-dec14700-c556-11eb-94d5-78e17a41a3a9.png">

The mislabeled in-cluster Postgres logs are still all labeled as err - need to do more research to figure out how to proceed there.

**Comment by askmeegs** [comment]
Also it seems like the Java severity is being mislogged as well -- (everything defaulting to Info) 
<img width="756" alt="java bad sverity" src="https://user-images.githubusercontent.com/3137106/120896086-ee3f9f00-c5ed-11eb-8930-2cc35ec0c294.png">


The scope of this work is bigger than I thought / more than just a bug fix. Unassigning myself so we can triage this as a full Cloud Logging overhaul for the app.

**Comment by bourgeoisor** [comment]
I have tested this with the latest commit and do not see any false positive, likely due to https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/501.

I do still see the PostgresDB instances mis-logging everything as error (due to Postgres' [default log destination](https://www.postgresql.org/docs/12/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHERE) being set to `stderr`). At first glance, it seems like we could redirect all to a syslog facility instead but I'm not sure if this implies the ability to separate info from errors.

Additionally, I'm seeing false negatives coming from the **frontend**:
![image](https://user-images.githubusercontent.com/3271352/127071740-a53cce1d-1127-4961-b7b1-6e19b7fd8e46.png)

I'm also not seeing any JSON payload for the false negatives on the Java side. Rather, the errors appear as plain text:
![image](https://user-images.githubusercontent.com/3271352/127072195-0f2a1257-822f-4399-9b05-21b2fe7112e2.png)
