### ISSUE TITLE
Cloud SQL instance is incorrectly suffixed "-multi"

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/bank-of-anthos#507]
Just reporting an extremely minor naming error that @askmeegs pointed out...

https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/368549b0edb4374765132fe21a87b91bcc37c295/extras/cloudsql/create_cloudsql_instance.sh#L16

**Comment by bourgeoisor** [comment]
This has been fixed in #523. Closing.
