### ISSUE TITLE
Support hosted Cloud Run

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#510]
The app currently relies on an assumption that the workloads are running in GCE/GKE - the Java micrometer startup code, for instance, calls the GCE Instance Metadata server to get the cluster name, zone, project ID. https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/src/ledgerwriter/src/main/java/anthos/samples/bankofanthos/ledgerwriter/LedgerWriterApplication.java#L106 

We could support the services running in hosted Cloud Run if we added a toggle to not set up java micrometer export.

Open questions 
- any changes needed for the python services? 
- where should the databases run - cloud sql? 
- service discovery - how can the frontend discover the backends?  
- configmaps - how does config get into the services?

**Comment by ptone** [comment]
There should be support for project ID in metadata, not sure what the specific micrometer failure might be: https://cloud.google.com/run/docs/reference/container-contract#metadata-server

CR is regional, not zonal - which could be the issue if the returned region is not passing some validation.

**Comment by marcfong** [comment]
I made the following changes to enable BOA to run on Cloud Run:

1. For services that send REST requests to other services, they need to be able to support HTTP(s) endpoints so this can be hardcoded or made configurable via a new ENV var.
2. Externalised BACKEND_TIMEOUT as an ENV var to have more control over the hard-coded 4 sec timeout.
3. Deleted the micrometer bean from all Java microservices. (Python microservices did not need any changes to stackdriver instrumentation)
4. Used Cloud Run secrets functionality to mount both the SSH public keys into the appropriate containers and filesystem paths.
5. For ledgerwriter server which needs both SSH private & public keys, you have to mount them to different paths as CR did not allow for both files to be mounted to the same "/root/.ssh/" directory.
