### ISSUE TITLE
Adjust CPU/Memory requests according to actual resource footprint

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#521]
1) Analyze a running version of Bank of Anthos to determine the actual CPU / Memory usage of each service    
2) Adjust CPU/Memory requests + limits in the Deployment YAMLs as needed
3) Document the overall CPU / Memory usage of the app

**Comment by bourgeoisor** [comment]
I deployed a long-term cluster to look at the current usage of resources. This is also somewhat related to #188.

**Comment by bourgeoisor** [comment]
After 14+ days, this is what the resource usage look like:

# accounts-db
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/3271352/156260001-aed402dc-6206-4f65-bd16-0208b5c9c900.png">

**CPU**: 0.003 / 0.1 / 0.5
**Memory**: 100 / 128 / 1024
**Disk**: 0.12 / 100

# balancereader

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/3271352/156260524-d9842d6b-dc45-4fed-a7bb-db888b9db76c.png">

**CPU**: 0.017 / 0.1 / 0.5
**Memory**: 500 / 512 / 1024
**Disk**: 0 / 4

# contacts

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/3271352/156260672-47e52ea3-8979-4df7-a01b-451d60d0138b.png">

**CPU**: 0.027 / 0.1 / 0.5
**Memory**: 67 / 62 / 256
**Disk**: 0 / 4

# frontend

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/3271352/156260825-f0cd99f4-f825-4864-9d64-f36b95237c86.png">

**CPU**: 0.12 / 0.1 / 0.5
**Memory**: 60 / 64 / 256
**Disk**: 0 / 4

# ledger-db

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/3271352/156260934-feb6496e-a3a7-454f-b934-c4ece375fdfb.png">

**CPU**: 0.007 / 0.1 / 0.5
**Memory**: 350 / 512 / 1024
**Disk**: 0.5 / 100

# ledgerwriter

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/3271352/156261188-17ea5390-7401-459f-b9a5-8b7dff318aa4.png">

**CPU**: 0.08 / 0.1 / 0.5
**Memory**: 420 / 512 / 1024
**Disk**: 0 / 4

# loadgenerator

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/3271352/156261715-e3d54aa9-ead1-43c9-b2cd-32730573f16d.png">

**CPU**: 0.018 / 0.1 / 0.5
**Memory**: 650 / 512 / 1024
**Disk**: 0 / 2

# transactionhistory

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/3271352/156261815-77934fdb-22e4-41ad-a5f1-0ae272ba6f42.png">

**CPU**: 0.017 / 0.1 / 0.5
**Memory**: 380 / 512 / 1024
**Disk**: 0 / 4

# userservice

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/3271352/156261924-d70653c2-981a-460a-b880-6aec55c42d38.png">

**CPU**: 0.233 / 0.1 / 0.5
**Memory**: 66 / 64 / 256
**Disk**: 0 / 4

**Comment by bourgeoisor** [comment]
This was done in https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/712
