### ISSUE TITLE
improvement: ensure input with more than 2 decimals are rounded up instead of truncated

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/bank-of-anthos#590]
### Describe request or inquiry 
- All the UI elements in the app only allow numbers with a maximum of 2 decimal points
- However, one could submit a request via the API directly with a number having more than 2 decimal points `(e.g: 5.23756)`
- When this is happens, the app truncates everything beyond the 2 decimal points `(e.g: 5.23756 -> 5.23)`
- Ideally we would want it to be rounded up `(e.g: 5.23756 -> 5.24)`

### What purpose/environment will this feature serve? 
- It's a minor improvement to ensure the sanity of the banking application
- This came off from a [comment](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/548#pullrequestreview-831854261) in this PR https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/548

**Comment by bourgeoisor** [comment]
Personally I don't think we should be rounding (e.g creating money out of thin air), and think we should continue truncating as "work as intended". The idea here is that dollar amounts below 0.01 aren't meaningful constructs and are inherently rounding or computational errors in the first place. We should either discard that superfluous data (truncating) or return an error. Given the nature of this app and the fact that this only affect non-frontend transactions, I'll close as WAI.
