### ISSUE TITLE
Add Cloud Deploy example/support

### ISSUE THREAD

**Issue by mans0954** [GoogleCloudPlatform/bank-of-anthos#596]
### Describe request or inquiry 

Google has recently introduced [Cloud Deploy](https://cloud.google.com/deploy).

In [this blog post](https://cloud.google.com/blog/topics/developers-practitioners/develop-and-debug-kubernetes-microservice-applications-fast-with-google-cloud) google cites Bank of Anthos as an example of using Skaffold modules with a micro-services architecture:

> To see Skaffold modules implemented in a larger example, see the Bank of Anthos application. It has 5+ larger microservices configured as Skaffold modules and is fully supported by Cloud Code IDEs. This is a great example of a large application that can be developed with Cloud Code and deployed with Cloud Deploy using the same Skaffold configuration.

I would like to see documentation and/or examples of best practice use of Cloud Deploy with Skaffold modules in a microservices architecture as I was looking into this last month and it was not at all clear that there was an elegant way of achieving this. Including other tools such as Kustomize (#486) and Cloud Build in this would also be helphul.

### What purpose/environment will this feature serve? 

This will help confused customers navigate the smorgasbord of tools Google expects customers to be able to assemble into something functional.

**Comment by bourgeoisor** [comment]
I agree that a full-fledge Kustomize + Cloud Deploy support would be ideal. Kustomize support (#486) is in the works for 2022. Cloud Deploy for Bank of Anthos is TBD as of currently.

**Comment by bourgeoisor** [comment]
This is still planned before EoY.

**Comment by bourgeoisor** [comment]
Thanks to the wonderful work that @aablsk has done, Bank of Anthos now supports a full Cloud Build + Cloud Deploy workflow as of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1221

The next release (`v0.6.0` very likely) will contain additional details on this, but note that this is not yet meant for public-consumption. Instructions can be found here: https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/iac/tf-multienv-cicd-anthos-autopilot, to be followed at your own risk :)

We are planning on releasing tail-end content (blog posts, etc) on this work

Closing this issue as resolved!

**Comment by mans0954** [comment]
Thank you very much, @aablsk and @bourgeoisor !
