### ISSUE TITLE
Access permissions to the Bucket bank-of-anthos-ci when deploying monolith

### ISSUE THREAD

**Issue by hudomju** [GoogleCloudPlatform/bank-of-anthos#610]
### Describe the bug 
When running "make monolith-deploy" as specified in the [docs](https://cloud.google.com/migrate/anthos/docs/migrating-monolith-vm-overview-setup), the VM gets created, but it does not install the ledgerservice because there are access permissions to the Bucket bank-of-anthos-ci. This are required in the line 90 of the [deploy-monolith.sh](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/src/ledgermonolith/init/install-script.sh) script file.

### To Reproduce 
Follow steps in [docs](https://cloud.google.com/migrate/anthos/docs/migrating-monolith-vm-overview-setup)

### Logs  
gsutil -m cp -r gs://${GCS_PATH}/* ${MONOLITH_DIR}
AccessDeniedException: 403 80714401348-compute@developer.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
CommandException: 1 file/object could not be transferred.

**Comment by bourgeoisor** [comment]
Sounds like there might be an IAM issue with the [migrated project](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/561). I'm looking into it.

**Comment by hudomju** [comment]
It seems that the issue still persists:

**Command**
# gsutil -m cp -r gs://${GCS_PATH}/* ${MONOLITH_DIR}

**Output**
Copying gs://bank-of-anthos-ci/monolith/install-script.sh...
Copying gs://bank-of-anthos-ci/monolith/jwt-secret.yaml...                      
Copying gs://bank-of-anthos-ci/monolith/ledgermonolith.env...                   
Copying gs://bank-of-anthos-ci/monolith/ledgermonolith.jar...                   
Copying gs://bank-of-anthos-ci/monolith/initdb/0_init_tables.sql...             
Copying gs://bank-of-anthos-ci/monolith/initdb/1_create_transactions.sh...      
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Finstall-script.sh?alt=media&generation=1639597668541614>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycdsRW7r97RJ20rF_Gmp05_4LOIFP4KU2IkmFdwrzAD5eXHLn9ANt4XICuNp-J5OSWoVzqXmXyO5ETfnwYmzfxiw', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Fjwt-secret.yaml?alt=media&generation=1639597671655915>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycdsc_Ntmod1xmZKcZpXCF523Ywb66FpDU7zuL0fuqrV-mng9-0WKgaKufxdpo16Zpq66_4LZZj4RN8xp4Vg91A', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Finitdb%2F0_init_tables.sql?alt=media&generation=1639597670166149>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycdsq-nNo6SGJlCbaDhyST0Upd7qyBuwA2AaIv9KlyFqn-5FF-IAIwd3ICp3zmWXVMh5K1s-1XE73AIzh-Td4-5c', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Fledgermonolith.jar?alt=media&generation=1639597666852190>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycdta4GOLUSnLO5LKoueTqehY1OyWvhsoNsX-nir5CMeh0OnuWH0UqllwL7J84-6o-X-2R_m5lg2oNtEb09oGpPM', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Fledgermonolith.env?alt=media&generation=1639597668537997>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycduDIDvxnu2WSSbkKFUmt7Oyx8QOq8bDKC6Gi3DLKGoXqZyGZscadsOP0SMz7mHroQ2gIAR5-OW7p7-GC25_Zg', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
AccessDeniedException: 403 HttpError accessing <https://storage.googleapis.com/download/storage/v1/b/bank-of-anthos-ci/o/monolith%2Finitdb%2F1_create_transactions.sh?alt=media&generation=1639597670158591>: response: <{'content-type': 'text/html; charset=UTF-8', 'vary': 'Origin, X-Origin', 'expires': 'Fri, 04 Feb 2022 13:36:20 GMT', 'content-length': '158', 'date': 'Fri, 04 Feb 2022 13:36:20 GMT', 'x-guploader-uploadid': 'ADPycdtkKXyfoOCQGjdWhe7-OjRwvBa3GBoBU7mx-uQLJk7FlCouhCsrMk8VYvZc8iikCs5c-Uq3Rb9xJ5gh4wJMUA', 'cache-control': 'private, max-age=0', 'status': '403', 'server': 'UploadServer'}>, content <qwiklabs-gcp-02-12be6d7b3968@qwiklabs-gcp-02-12be6d7b3968.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.>
CommandException: 6 files/objects could not be transferred.

**Comment by bourgeoisor** [comment]
Thank you for your patience-- I've added a few more read-only permissions.

**Comment by hudomju** [comment]
This is fixed, installation runs smoothly, I can curl the version on port 8080 but when I check the java app logs I see the following:

tail -f /var/log/monolith.log

2022-02-07 11:34:52 | [WARN] | run | Could not reach ledger database
2022-02-07 11:34:52 | [INFO] | getConnection | HikariPool-1 - Starting...
2022-02-07 11:34:53 | [WARN] | logExceptions | SQL Error: 0, SQLState: 08001
2022-02-07 11:34:53 | [ERROR] | logExceptions | Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections

Any idea what could have gone wrong?

**Comment by hudomju** [comment]
This is fixed, installation runs smoothly, I can curl the version on port 8080 but when I check the java app logs I see the following:

tail -f /var/log/monolith.log

2022-02-07 11:34:52 | [WARN] | run | Could not reach ledger database
2022-02-07 11:34:52 | [INFO] | getConnection | HikariPool-1 - Starting...
2022-02-07 11:34:53 | [WARN] | logExceptions | SQL Error: 0, SQLState: 08001
2022-02-07 11:34:53 | [ERROR] | logExceptions | Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections

Any idea what could have gone wrong?

**Comment by bourgeoisor** [comment]
Could you list the complete list of commands you run to get that setup?

The database is packaged / sandbox with the ledgermonolith in the same VM and shouldn't require anything more than deploying the VM itself to get it running. I just now on my end tried:
```
~ export PROJECT_ID=<project-id>
~ export ZONE=us-east1-b
~ git clone https://github.com/GoogleCloudPlatform/bank-of-anthos ${HOME}/bank-of-anthos
~ cd ${HOME}/bank-of-anthos
~ make monolith-deploy
```

And then SSH'd into the VM to tail the same log:
```
~ tail -f /var/log/monolith.log
2022-02-07 15:16:00 | [INFO] | <init> | Default credentials provider for Google Compute Engine.
2022-02-07 15:16:00 | [INFO] | <init> | Scopes in use by default credentials: [https://www.googleapis.com/auth/pubsub, https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data, https://www.googleapis.com/auth/datastore, https://www.googleapis.com/auth/sqlservice.admin, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/devstorage.read_write, https://www.googleapis.com/auth/cloudruntimeconfig, https://www.googleapis.com/auth/trace.append, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-vision, https://www.googleapis.com/auth/bigquery]
2022-02-07 15:16:00 | [INFO] | gcpProjectIdProvider | The default project ID is <project-id>
2022-02-07 15:16:00 | [INFO] | <init> | Exposing 2 endpoint(s) beneath base path '/actuator'
2022-02-07 15:16:01 | [INFO] | log | Starting ProtocolHandler ["http-nio-8080"]
2022-02-07 15:16:01 | [INFO] | start | Tomcat started on port(s): 8080 (http) with context path ''
2022-02-07 15:16:01 | [INFO] | onApplicationEvent | Triggering deferred initialization of Spring Data repositories…
2022-02-07 15:16:01 | [INFO] | onApplicationEvent | Spring Data repositories initialized!
2022-02-07 15:16:01 | [INFO] | logStarted | Started LedgerMonolithApplication in 15.824 seconds (JVM running for 18.949)
2022-02-07 15:16:01 | [STARTUP] | main | Started LedgerMonolith service. Log level is: INFO
```

You can see the database is running:
```
~ ps aux | grep postgres
postgres  8404  0.0  0.7 212272 27420 ?        S    15:15   0:00 /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/postgresql.conf
```

**Comment by hudomju** [comment]
Great, it works now - not sure what the issue was before, but it's gone now. Thanks for your help!

**Comment by bourgeoisor** [comment]
The VM takes a minute or two to fully boot up; it -may- be that. I'll close the issue, but do feel free to let me know if you have any further issues!
