### ISSUE TITLE
Merge balancereader and transactionhistory services

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#69]
There is much duplicated code between BalanceReader and TransactionHistory.  If we were to merge the two services, we could reduce the code complexity and the resource footprint of the application.

Currently, the two services both:

- Read every transaction in the database
  - calculate a set of values
  - store the results
- Poll for new transactions
  - update the associated values
- Serve REST requests to retrieve said values  

The only difference what value is being calculated:

- BalanceReader:  a running account balance
- TransactionHistory:  a running list of historical transactions

We could easily merge these two services and simplify the application and codebase.  As an example:

`AccountsReader`
- `/accounts/<accountid>/balance` GET
- `/accounts/<accountid>/transactions` GET

**Comment by DanSanche** [comment]
This would be technically easy enough, but there are design reasons to want to keep them separate: 
- allow users to scale these two services independently
- add different security settings to each of them 
- allow other services to talk to balancereader, but not transactionhistory

I'd say we shouldn't worry too much about combining them unless we get feedback to reduce the number of services
