### ISSUE TITLE
Update accounts-db to not allow blank contact labels

### ISSUE THREAD

**Issue by djmailhot** [GoogleCloudPlatform/bank-of-anthos#83]
Currently, the backend allows contacts without a label.  We should update the backend to always save contacts with a label.

The frontend shows that contact/external account labels are optional.  If no label is provided then the contact is not saved.

**Comment by DanSanche** [comment]
I added regex validation for the label to the contacts service in this (already merged) PR: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/78

The `accounts-db` may not be marking it as a required field, however
