### ISSUE TITLE
Use supported version of OpenJDK

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/bank-of-anthos#879]
## Describe request or inquiry 

* Upgrade the Java microservices from OpenJDK `17` to a supported version.

## Background

* According to [this page](https://jdk.java.net/17/), OpenJDK 17 is not recommended for use in production.
* [This page](https://jdk.java.net/) suggests which OpenJDK is ready for use.
* The [Bank of Anthos development guide](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/release/v0.5.5/docs/development.md#install-tools) currently suggests using OpenJDK 17.
* We are still able to download OpenJDK 17 from [this archive](https://jdk.java.net/archive/) — so I've selected a low priority for this issue.
* In [#712](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/712), we upgraded all Java services from `1.8` to `1.17` (`JDK 17`). We may have to do something similar.
* This issue was inspired by [#874](https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/874).

### What purpose/environment will this feature serve? 

* This change impacts all deployments of Bank of Anthos.
* This change will reduce the vulnerability of Java services.

**Comment by bourgeoisor** [comment]
That's interesting, given that 17 is an LTS release and supported until 2029: https://en.wikipedia.org/wiki/Java_version_history

**Comment by mathieu-benoit** [comment]
Maybe 18? With Eclipse Adoptium?

We just moved to `openjdk:18` with Online Boutique https://github.com/GoogleCloudPlatform/microservices-demo/pull/1007

**Comment by vanberge** [comment]
Looks like I ran into an issue related to this... 
Using a CloudShell terminal, I executed  "make monolith build", the builds fail.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.256 s
[INFO] Finished at: 2022-09-02T15:01:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project ledgermonolith: Fatal error compiling: error: invalid target release: 17 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
make: *** [Makefile:53: monolith-build] Error 1

When I update java version to version 11 in all the pom.xml files, the build completes successfully.  Maybe there's a reasonably easy way to add OpenJDK v17 to CloudShell instances; but I'm not sure the best way to proceed.

**Comment by mathieu-benoit** [comment]
Hi @vanberge, with the coming PR #991 we will soon close this one, but I feel that the issue is reporting should be a different issue, could you please file a new issue with that? Thanks!
