### ISSUE TITLE
Forward metrics from EKS cluser

### ISSUE THREAD

**Issue by paulwilljones** [GoogleCloudPlatform/bank-of-anthos#885]
I'm attempting to run Bank of Anthos in EKS and forward metrics from the services to GCP Operations.

I have registered the cluster in the GKE Hub and logged in using Google Identity.

After following the instructions from [non-gke-kubernetes-clusters](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/environments.md#non-gke-kubernetes-clusters), I have a service account key (with the required permissions) in the cluster which is mounted to the workloads, with `GOOGLE_APPLICATION_CREDENTIALS` set to `key.json`.

`ENABLE_METRICS` and `ENABLE_TRACING` are `true`, however, I am seeing errors in the logs for `ledgerwriter` and other services trying to forward metrics to GCP.

```sh
2022-08-03 11:51:00.404  WARN [,,] 1 --- [trics-publisher] i.m.s.StackdriverMeterRegistry           : Failed to pre populate verified descriptors for

com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/
...
```

It seems that ledgerwriter, balancerreader and transactionhistory are using the `MetadataConfig` to get the `projectId`, however, is this going to work outside of GCP?
https://github.com/GoogleCloudPlatform/bank-of-anthos/search?q=getProjectId

Additionally, I've deployed the logging and monitoring agents for attached clusters, but that shouldn't be necessary here as the services a forwarding their own metrics.
https://cloud.google.com/anthos/clusters/docs/attached/how-to/logging-and-monitoring#installing_the_logging_agent

**Comment by minherz** [comment]
Please, try defining the GCP project id explicitly using `GOOGLE_CLOUD_PROJECT` environment variable (set for your deployments similar to `ENABLE_METRICS` and `ENABLE_TRACING` variables).
This variable allows implicitly provide the information as a replacement of using metadata service.

**Comment by bourgeoisor** [comment]
This issue is getting stale, so I'm going to close it.
Paul: feel free to reopen if you still need help.
