### ISSUE TITLE
how to do a performance test against BoA?

### ISSUE THREAD

**Issue by ryuxin** [GoogleCloudPlatform/bank-of-anthos#889]
Does BoA contain any performance testing, such as workload generator and performance report around throughput, latency, etc?

If not, any suggestions to implement such a performance measurement?

Thanks a lot!

**Comment by bourgeoisor** [comment]
Thank you for the question! It seems to be twofold:

1) **Workload generation**: There is a locust load generation service (called [loadgenerator](https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/src/loadgenerator)) which creates fake transactions (and can be extended to increase load further) over time. It is deployed by default.

2) **Performance reports**: Bank of Anthos is currently instrumented with Google Cloud Operations (and soon Apigee) which provides you with dashboards, charts and metrics surrounding throughput and latency (among other things). There are no plans at the moment for other instrumentations.

Let me know if that answers your question!
