### ISSUE TITLE
Broken: Pods on CrashLoopBackOff state

### ISSUE THREAD

**Issue by hudomju** [GoogleCloudPlatform/bank-of-anthos#908]
### Describe the bug 

When deploying the application on Kubernetes some pods are on CrashLoopBackOff

NAME                                                     READY   STATUS             RESTARTS         AGE
accounts-db-0                                      1/1     Running            0                149m
contacts-6d546d99dc-t5rf8               0/1     CrashLoopBackOff   33 (3m29s ago)   148m
frontend-5bf85cbdb7-zv56c               0/1     CrashLoopBackOff   33 (2m51s ago)   148m
loadgenerator-678f99897b-2kw2t      1/1     Running            0                148m
userservice-7b8b6c8885-9trrl             0/1     CrashLoopBackOff   33 (3m41s ago)   149m

### To Reproduce

https://cloud.google.com/migrate/containers/docs/migrating-monolith-vm-overview-setup#deploy

### Logs  

The pod fails to start, it goes to CrashLoopBackOff, and logs don't help.

### Environment 
GKE  v. 1.22.11-gke.400
us-central1-b

### Exposure 
Docs don't work https://cloud.google.com/migrate/containers/docs/migrating-monolith-vm-overview-setup
Lab AHYBRID111 from the Anthos class does not work

**Comment by hudomju** [comment]
@bourgeoisor thoughts?

**Comment by hudomju** [comment]
It seems that the issue was introduced in release/v0.5.6. I think the images are not available or they might not have the right permissions. I just tested release/v0.5.5 and it's working fine.

**Comment by bourgeoisor** [comment]
Tested quickly on a fresh cluster, looks like `0.5.6` is deploying fine:

```
~ kubectl apply -f ./extras/jwt/jwt-secret.yaml
  kubectl apply -f ./kubernetes-manifests
  
secret/jwt-key created
statefulset.apps/accounts-db created
service/accounts-db created
configmap/accounts-db-config created
deployment.apps/balancereader created
service/balancereader created
configmap/environment-config created
configmap/service-api-config created
configmap/demo-data-config created
deployment.apps/contacts created
service/contacts created
deployment.apps/frontend created
service/frontend created
statefulset.apps/ledger-db created
configmap/ledger-db-config created
service/ledger-db created
deployment.apps/ledgerwriter created
service/ledgerwriter created
deployment.apps/loadgenerator created
deployment.apps/transactionhistory created
service/transactionhistory created
deployment.apps/userservice created
service/userservice created
```
```
~ k get pods
NAME                                  READY   STATUS    RESTARTS   AGE
accounts-db-0                         1/1     Running   0          102s
balancereader-798cbd4b8b-g5m69        1/1     Running   0          99s
contacts-6d546d99dc-vqfgh             1/1     Running   0          98s
frontend-5bf85cbdb7-ttlvl             1/1     Running   0          98s
ledger-db-0                           1/1     Running   0          97s
ledgerwriter-849685fd45-79kfs         1/1     Running   0          96s
loadgenerator-678f99897b-lnnz4        1/1     Running   0          96s
transactionhistory-79d9d85b88-pzzr5   1/1     Running   0          96s
userservice-7b8b6c8885-lccr5          1/1     Running   0          95s
```

I'm going to try with that tutorial specifically, though.

**Comment by bourgeoisor** [comment]
I think I found the issue. https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/src/ledgermonolith/config.yaml#L17-L23 is not up-to-date with latest changes. Will put up a fix--

**Comment by hudomju** [comment]
I re-run the lab with the updated version and it's working up to the point where we rebuild the java package and modify the Dockerfile to include the updated ledgermonolith-service. When I deploy it into the cluster the service is no longer accessible. These are some of the logs:
![Screenshot logs](https://user-images.githubusercontent.com/1647360/186933373-93131cab-dc27-4d3c-bb14-8fc9ad071dca.png)
