### ISSUE TITLE
GitHub Action Link is 404

### ISSUE THREAD

**Issue by justingrayston** [GoogleCloudPlatform/bank-of-anthos#94]
Under [Continuous Integration](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/docs/development.md#continuous-integration) section the link to the GitHub actions https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/docs/.github/workflows is 404.

Did someone just forget to `git add` ?

**Comment by murog** [comment]
Looks like a typo, the correct link is https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/master/.github/workflows. Thanks for surfacing this!
